// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtd16HT8-JPg5Jh2vIFMj7HBgqlH2jkVM',
    appId: '1:1068224636281:web:8f6e5fa54c5be4fa5dfba8',
    messagingSenderId: '1068224636281',
    projectId: 'pokeapi-77b59',
    authDomain: 'pokeapi-77b59.firebaseapp.com',
    storageBucket: 'pokeapi-77b59.firebasestorage.app',
    measurementId: 'G-V0L7ED7CVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYO0Cx7UWRHfiLS-Ath3zwnYtObZt6ey0',
    appId: '1:1068224636281:android:3e60553ac41b85cd5dfba8',
    messagingSenderId: '1068224636281',
    projectId: 'pokeapi-77b59',
    storageBucket: 'pokeapi-77b59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-fcM4s7IX15voMaZU9m0LlukR4muk38',
    appId: '1:1068224636281:ios:26ecf5249938fca05dfba8',
    messagingSenderId: '1068224636281',
    projectId: 'pokeapi-77b59',
    storageBucket: 'pokeapi-77b59.firebasestorage.app',
    iosClientId: '1068224636281-37tfnq36vmfr5p94k4ainddim60kudd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0-fcM4s7IX15voMaZU9m0LlukR4muk38',
    appId: '1:1068224636281:ios:26ecf5249938fca05dfba8',
    messagingSenderId: '1068224636281',
    projectId: 'pokeapi-77b59',
    storageBucket: 'pokeapi-77b59.firebasestorage.app',
    iosClientId: '1068224636281-37tfnq36vmfr5p94k4ainddim60kudd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtd16HT8-JPg5Jh2vIFMj7HBgqlH2jkVM',
    appId: '1:1068224636281:web:2db65a43f823f05a5dfba8',
    messagingSenderId: '1068224636281',
    projectId: 'pokeapi-77b59',
    authDomain: 'pokeapi-77b59.firebaseapp.com',
    storageBucket: 'pokeapi-77b59.firebasestorage.app',
    measurementId: 'G-CWK0YWJRTJ',
  );
}
